### ISSUE TITLE
In one wofost model, the'apply_npk' event and the 'irrigate' event do not work.

### ISSUE THREAD

**Issue by jjanggu1993** [ajwdewit/pcse#38]
I'm trying to modify agromanagement file for wofost model and change apply_npk values and irrigation like this:

```
agro = '''
- 1988-01-01:
    CropCalendar:
        crop_name: wheat
        variety_name: winter-wheat
        crop_start_date: 1988-01-01
        crop_start_type: emergence
        crop_end_date:
        crop_end_type: maturity
        max_duration: 300
    TimedEvents:
    -   event_signal: irrigate
        name: Irrigation application table
        comment: All irrigation amounts in cm
        events_table:
        - 1988-03-05: {amount: 10, efficiency: 0.7}
        - 1988-03-20: {amount: 10, efficiency: 0.7}
        - 1988-04-01: {amount: 10, efficiency: 0.7}
        - 1988-04-10: {amount: 10, efficiency: 0.7}
        - 1988-05-10: {amount: 10, efficiency: 0.7}
    -   event_signal: apply_npk
        name:  Timed N/P/K application table
        comment: All fertilizer amounts in kg/ha
        events_table:
        - 1988-04-29: {N_amount: 0., P_amount: 40., K_amount: 20., N_recovery: 0.7, P_recovery: 0.7, K_recovery: 0.7}
        - 1988-06-16: {N_amount: 0., P_amount: 10., K_amount: 20., N_recovery: 0.7, P_recovery: 0.7, K_recovery: 0.7}
    StateEvents: null
'''
agro = yaml.safe_load(agro)
```

`Wofost71_WLP_FD` doesn't respond to apply_NPK events. (only respond to irrigate events)

Howerver, when i use `wofost = Engine(params, weather, agro, config="Wofost71_NPK.conf")`,  it doesn't respond to irrigate events, but respond to apply_NPK events

`Wofost71_PP` model doesn't react to both events.

**my question is, is there a wofost model that responds to both events?** Or is it not implemented yet? Or is it a bug?
