### ISSUE TITLE
Applying fertilizer seems to have no impact on growth of a crop in Wofost80_NWLP_FD_beta

### ISSUE THREAD

**Issue by Tessavankleef** [ajwdewit/pcse#60]
Dear all,

I am trying to use PSCE to look at the effects of fertilizer on the growth of a crop in a specific crop rotation. To do this I used the [Notebook #7] (https://github.com/ajwdewit/pcse_notebooks/blob/master/07%20Running%20crop%20rotations.ipynb) and changed a few things:

- Changed WOFOST72 to Wofost80_NWLP_FD_beta accessing the package from the develop branch (to solve the 'DVS' error)
- Set the parameters that were missing in the provided data (RKUPTAKEMAX, RNUPTAKEMAX, RPUPTAKEMAX, NAVAILI, PAVAILI, KAVAILI).

Then, I added the fertilization to the agromanagement as follows:

```
agro_yaml_fert = """
AgroManagement:
- 2004-08-01:
    CropCalendar:
        crop_name: wheat
        variety_name: Winter_wheat_101
        crop_start_date: 2004-09-15
        crop_start_type: sowing
        crop_end_date:
        crop_end_type: maturity
        max_duration: 300
    TimedEvents: null
    StateEvents: 
    -   event_signal: apply_npk
        event_state: DVS
        zero_condition: rising
        name: DVS-based N/P/K application table
        comment: all fertilizer amounts in kg/ha
        events_table:
        - 0.3: {N_amount : 1, P_amount: 3, K_amount: 4}
        - 0.6: {N_amount: 11, P_amount: 13, K_amount: 14}
        - 1.12: {N_amount: 21, P_amount: 23, K_amount: 24}
- 2005-09-01:
    CropCalendar: null
    TimedEvents: null
    StateEvents: null
- 2006-03-01:
    CropCalendar:
        crop_name: sugarbeet
        variety_name: Sugarbeet_601
        crop_start_date: 2006-04-15
        crop_start_type: sowing
        crop_end_date:
        crop_end_type: maturity
        max_duration: 200
    TimedEvents:
    -   event_signal: apply_n
        name: Nitrogen application table
        comment: All nitrogen amounts in g N m-2
        events_table:
        - 2006-04-10: {amount: 10, recovery: 0.7}
        - 2006-05-05: {amount: 5, recovery: 0.7}
    StateEvents: null
"""
```
However, the outcome does not seem to change. Am I doing something wrong here or is the model simply not able yet to take fertilization into account? I have attached my notebook. Moreover, I have tried different values for the missing parameters, but that does not seem to solve the issue either. 

Thanks in advance,

Tessa
[WOFOST 8.0 implementation and comparison.zip](https://github.com/ajwdewit/pcse/files/8620386/WOFOST.8.0.implementation.and.comparison.zip)
